import { Program, Statement, Expression, BinaryExpression, UnaryExpression, 
         AssignmentExpression, CallExpression, MemberExpression, NewExpression,
         SuperExpression, ArrayExpression, ObjectExpression, Literal, Identifier, LambdaExpression,
         ConditionalExpression, SwitchStatement, SwitchCase, TryStatement, 
         CatchClause, ForStatement, ForEachStatement, BlockStatement, 
         VariableDeclaration, FunctionDeclaration, ClassDeclaration, MethodDeclaration,
         FieldDeclaration, InterfaceDeclaration, IfStatement, ElseClause, 
          WhileStatement, ReturnStatement, ThrowStatement, BreakStatement, 
         ContinueStatement, ImportStatement, ExportStatement, ExpressionStatement,
         DoWhileStatement } from "../parser/AST";

export class JavaScriptEmitter {
  private output = "";
  private indent = 0;
  private variables: Set<string> = new Set();
  private functions: Set<string> = new Set();
  private classes: Set<string> = new Set();

  emit(program: Program): string {
    this.output = "";
    this.indent = 0;
    this.variables = new Set();
    this.functions = new Set();
    this.classes = new Set();

    this.emitRuntimeHelpers();
    
    for (const stmt of program.body) {
      this.emitStatement(stmt);
    }
    
    return this.output;
  }

  private emitRuntimeHelpers(): void {
    this.output += `// Generated by BetaScript Compiler\n`;
    this.output += `const __fs = require("fs");\n`;
    this.output += `const __pasang = (proto, nama, fn) => { if (!Object.prototype.hasOwnProperty.call(proto, nama)) Object.defineProperty(proto, nama, { value: fn, configurable: true }); };\n`;
    this.output += `const __pasangGet = (proto, nama, fn) => { if (!Object.prototype.hasOwnProperty.call(proto, nama)) Object.defineProperty(proto, nama, { get: fn, configurable: true }); };\n`;
    this.output += `__pasang(String.prototype, "gede", function() { return this.toString().toUpperCase(); });\n`;
    this.output += `__pasang(String.prototype, "kecil", function() { return this.toString().toLowerCase(); });\n`;
    this.output += `__pasang(String.prototype, "pisah", function(separator) { return this.toString().split(separator); });\n`;
    this.output += `__pasang(String.prototype, "ganti", function(search, replace) { return this.toString().replace(search, replace); });\n`;
    this.output += `__pasang(String.prototype, "cocok", function(pattern) { return this.toString().match(pattern); });\n`;
    this.output += `__pasangGet(String.prototype, "sebrapa", function() { return this.length; });\n`;
    this.output += `__pasang(Array.prototype, "petakan", function(fn) { return this.map(fn); });\n`;
    this.output += `__pasang(Array.prototype, "saring", function(fn) { return this.filter(fn); });\n`;
    this.output += `__pasang(Array.prototype, "kurangi", function(fn, init) { return arguments.length > 1 ? this.reduce(fn, init) : this.reduce(fn); });\n`;
    this.output += `__pasang(Array.prototype, "urutin", function(fn) { return this.sort(fn); });\n`;
    this.output += `__pasang(Array.prototype, "gabung", function(separator) { return this.join(separator); });\n`;
    this.output += `__pasangGet(Array.prototype, "sebrapa", function() { return this.length; });\n`;
    this.output += `const __runtime = {\n`;
    this.output += this.indentString() + `teriak: (...args) => console.log(...args),\n`;
    this.output += this.indentString() + `bisik: (msg) => process.stdout.write(String(msg)),\n`;
    this.output += this.indentString() + `dengerin: (msg) => require('readline-sync').question(msg),\n`;
    this.output += this.indentString() + `sebrapa: (arr) => arr?.length ?? 0,\n`;
    this.output += this.indentString() + `ape: (val) => typeof val,\n`;
    this.output += this.indentString() + `itungan: (val) => Number(val),\n`;
    this.output += this.indentString() + `omongan: (val) => String(val),\n`;
    this.output += this.indentString() + `kumpulin: (...items) => Array(...items),\n`;
    this.output += this.indentString() + `acak: () => Math.random(),\n`;
    this.output += this.indentString() + `tidur: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),\n`;
    this.output += this.indentString() + `semua: (promises) => Promise.all(promises),\n`;
    this.output += this.indentString() + `balap: (promises) => Promise.race(promises),\n`;
    this.output += this.indentString() + `peta: (entries) => new Map(entries),\n`;
    this.output += this.indentString() + `himpunan: (values) => new Set(values),\n`;
    this.output += this.indentString() + `peta_lemah: (entries) => new WeakMap(entries),\n`;
    this.output += this.indentString() + `himpunan_lemah: (values) => new WeakSet(values)\n`;
    this.output += `};\n\n`;
    this.output += `const http = { ambil: (url, options) => fetch(url, options), kirim: (url, data, options = {}) => fetch(url, { ...options, method: options.method || "POST", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, body: typeof data === "string" ? data : JSON.stringify(data) }) };\n`;
    this.output += `const file = { baca: (p) => __fs.promises.readFile(p, "utf8"), tulis: (p, data) => __fs.promises.writeFile(p, data, "utf8"), ada: (p) => __fs.existsSync(p) };\n`;
    this.output += `const matematika = { pi: Math.PI, akar: Math.sqrt, acak: Math.random, bulat: Math.round, lantai: Math.floor, atap: Math.ceil, mutlak: Math.abs, maksimal: Math.max, minimal: Math.min };\n`;
    this.output += `const teks = { gede: (v) => String(v).toUpperCase(), kecil: (v) => String(v).toLowerCase(), pisah: (v, s) => String(v).split(s), ganti: (v, a, b) => String(v).replace(a, b), cocok: (v, pola) => String(v).match(pola) };\n`;
    this.output += `const deret = { petakan: (v, fn) => v.map(fn), saring: (v, fn) => v.filter(fn), kurangi: (v, fn, init) => init === undefined ? v.reduce(fn) : v.reduce(fn, init), urutin: (v, fn) => v.sort(fn) };\n`;
    this.output += `const waktu = { sekarang: () => new Date(), format: (v) => new Date(v).toISOString(), tahun: (v = new Date()) => new Date(v).getFullYear(), bulan: (v = new Date()) => new Date(v).getMonth() + 1, tanggal: (v = new Date()) => new Date(v).getDate() };\n`;
    this.output += `const json = { parse: JSON.parse, stringify: JSON.stringify };\n`;
    this.output += `const teriak = __runtime.teriak;\n`;
    this.output += `const bisik = __runtime.bisik;\n`;
    this.output += `const dengerin = __runtime.dengerin;\n`;
    this.output += `const sebrapa = __runtime.sebrapa;\n`;
    this.output += `const ape = __runtime.ape;\n`;
    this.output += `const itungan = __runtime.itungan;\n`;
    this.output += `const omongan = __runtime.omongan;\n`;
    this.output += `const kumpulin = __runtime.kumpulin;\n`;
    this.output += `const acak = __runtime.acak;\n`;
    this.output += `const tidur = __runtime.tidur;\n\n`;
    this.output += `const semua = __runtime.semua;\n`;
    this.output += `const balap = __runtime.balap;\n`;
    this.output += `const peta = __runtime.peta;\n`;
    this.output += `const himpunan = __runtime.himpunan;\n`;
    this.output += `const peta_lemah = __runtime.peta_lemah;\n`;
    this.output += `const himpunan_lemah = __runtime.himpunan_lemah;\n\n`;
  }

  private emitStatement(stmt: Statement): void {
    switch (stmt.type) {
      case "EmptyStatement":
        break;
      case "VariableDeclaration":
        this.emitVariableDeclaration(stmt);
        break;
      case "FunctionDeclaration":
        this.emitFunctionDeclaration(stmt);
        break;
      case "ClassDeclaration":
        this.emitClassDeclaration(stmt);
        break;
      case "InterfaceDeclaration":
        break;
      case "IfStatement":
        this.emitIfStatement(stmt);
        break;
      case "WhileStatement":
        this.emitWhileStatement(stmt);
        break;
      case "DoWhileStatement":
        this.emitDoWhileStatement(stmt);
        break;
      case "ForStatement":
        this.emitForStatement(stmt);
        break;
      case "ForEachStatement":
        this.emitForEachStatement(stmt);
        break;
      case "SwitchStatement":
        this.emitSwitchStatement(stmt);
        break;
      case "TryStatement":
        this.emitTryStatement(stmt);
        break;
      case "ReturnStatement":
        this.emitReturnStatement(stmt);
        break;
      case "ThrowStatement":
        this.emitThrowStatement(stmt);
        break;
      case "BreakStatement":
        this.emitLine("break;");
        break;
      case "ContinueStatement":
        this.emitLine("continue;");
        break;
      case "ImportStatement":
        this.emitImportStatement(stmt);
        break;
      case "ExportStatement":
        this.emitExportStatement(stmt);
        break;
      case "ExpressionStatement":
        this.emitExpressionStatement(stmt);
        break;
      case "BlockStatement":
        this.emitBlockStatement(stmt);
        break;
    }
  }

  private emitVariableDeclaration(stmt: VariableDeclaration): void {
    const keyword = stmt.kind === "ane" ? "let" : "const";
    const name = stmt.name;
    this.variables.add(name);
    
    if (stmt.initializer) {
      this.emitLine(`${keyword} ${name} = ${this.emitExpression(stmt.initializer)};`);
    } else {
      this.emitLine(`${keyword} ${name};`);
    }
  }

  private emitFunctionDeclaration(stmt: FunctionDeclaration): void {
    const asyncKeyword = stmt.isAsync ? "async " : "";
    const exportKeyword = stmt.isExported ? "export " : "";
    const name = stmt.name;
    this.functions.add(name);
    
    const params = stmt.parameters.map(p => `${p.isRest ? "..." : ""}${p.name}`).join(", ");
    this.emitLine(`${exportKeyword}${asyncKeyword}function ${name}(${params}) {`);
    this.indent++;
    this.emitBlockStatement(stmt.body);
    this.indent--;
    this.emitLine("}");
  }

  private emitClassDeclaration(stmt: ClassDeclaration): void {
    this.classes.add(stmt.name);
    let classStr = "class " + stmt.name;
    
    if (stmt.superclass) {
      classStr += " extends " + stmt.superclass;
    }
    
    this.emitLine(classStr + " {");
    this.indent++;
    
    for (const member of stmt.members) {
      this.emitClassMember(member);
    }
    
    this.indent--;
    this.emitLine("}");
  }

  private emitClassMember(member: MethodDeclaration | FieldDeclaration): void {
    if (member.type === "MethodDeclaration") {
      const staticKeyword = member.isStatic ? "static " : "";
      
      if (member.kind === "method") {
        const isAsync = member.body.statements.some(s => 
          s.type === "FunctionDeclaration" && s.isAsync
        ) || member.body.statements.some(s => 
          s.type === "ExpressionStatement" && 
          s.expression.type === "CallExpression" &&
          s.expression.callee.type === "Identifier" &&
          s.expression.callee.name === "tungguin"
        );
        
        const asyncKeyword = isAsync ? "async " : "";
        const params = member.parameters.map(p => `${p.isRest ? "..." : ""}${p.name}`).join(", ");
        this.emitLine(`${staticKeyword}${asyncKeyword}${member.name}(${params}) {`);
        this.indent++;
        this.emitBlockStatement(member.body);
        this.indent--;
        this.emitLine("}");
      } else {
        const params = member.parameters.map(p => `${p.isRest ? "..." : ""}${p.name}`).join(", ");
        this.emitLine(`${staticKeyword}constructor(${params}) {`);
        this.indent++;
        this.emitBlockStatement(member.body);
        this.indent--;
        this.emitLine("}");
      }
    } else {
      const staticKeyword = member.isStatic ? "static " : "";
      const visibility = this.getVisibility(member.visibility);
      
      if (member.initializer) {
        this.emitLine(`${staticKeyword}${visibility}${member.name} = ${this.emitExpression(member.initializer)};`);
      } else {
        this.emitLine(`${staticKeyword}${visibility}${member.name};`);
      }
    }
  }

  private getVisibility(vis: "public" | "private" | "protected"): string {
    switch (vis) {
      case "private": return "#";
      case "protected": return "#";
      default: return "";
    }
  }

  private emitIfStatement(stmt: IfStatement): void {
    this.emitLine(`if (${this.emitExpression(stmt.test)}) {`);
    this.indent++;
    this.emitBlockStatement(stmt.consequent);
    this.indent--;
    this.emitLine("}");
    
    if (stmt.alternate) {
      if (stmt.alternate.ifStatement) {
        this.emitIfStatement(stmt.alternate.ifStatement);
      } else if (stmt.alternate.block) {
        this.emitLine("else {");
        this.indent++;
        this.emitBlockStatement(stmt.alternate.block);
        this.indent--;
        this.emitLine("}");
      }
    }
  }

  private emitWhileStatement(stmt: WhileStatement): void {
    this.emitLine(`while (${this.emitExpression(stmt.test)}) {`);
    this.indent++;
    this.emitBlockStatement(stmt.body);
    this.indent--;
    this.emitLine("}");
  }

  private emitDoWhileStatement(stmt: DoWhileStatement): void {
    this.emitLine("do {");
    this.indent++;
    this.emitBlockStatement(stmt.body);
    this.indent--;
    this.emitLine(`} while (${this.emitExpression(stmt.test)});`);
  }

  private emitForStatement(stmt: ForStatement): void {
    const init = this.emitForInit(stmt.init);
    this.emitLine(`for (${init}; ${this.emitExpression(stmt.test)}; ${this.emitExpression(stmt.update)}) {`);
    this.indent++;
    this.emitBlockStatement(stmt.body);
    this.indent--;
    this.emitLine("}");
  }

  private emitForInit(init: VariableDeclaration): string {
    const keyword = init.kind === "ane" ? "let" : "const";
    if (init.initializer) {
      return `${keyword} ${init.name} = ${this.emitExpression(init.initializer)}`;
    }
    return `${keyword} ${init.name}`;
  }

  private emitForEachStatement(stmt: ForEachStatement): void {
    const keyword = stmt.kind === "ane" ? "let" : "const";
    this.emitLine(`for (${keyword} ${stmt.variable} of ${this.emitExpression(stmt.iterable)}) {`);
    this.indent++;
    this.emitBlockStatement(stmt.body);
    this.indent--;
    this.emitLine("}");
  }

  private emitSwitchStatement(stmt: SwitchStatement): void {
    this.emitLine(`switch (${this.emitExpression(stmt.discriminant)}) {`);
    this.indent++;
    
    for (const caseItem of stmt.cases) {
      if (caseItem.test === null) {
        this.emitLine("default:");
      } else {
        this.emitLine(`case ${this.emitExpression(caseItem.test)}:`);
      }
      this.indent++;
      for (const caseStmt of caseItem.consequent) {
        this.emitStatement(caseStmt);
      }
      this.indent--;
    }
    
    this.indent--;
    this.emitLine("}");
  }

  private emitTryStatement(stmt: TryStatement): void {
    this.emitLine("try {");
    this.indent++;
    this.emitBlockStatement(stmt.block);
    this.indent--;
    
    if (stmt.handler) {
      const param = stmt.handler.param ?? "";
      this.emitLine(`} catch (${param}) {`);
      this.indent++;
      this.emitBlockStatement(stmt.handler.block);
      this.indent--;
    }
    
    if (stmt.finalizer) {
      this.emitLine("} finally {");
      this.indent++;
      this.emitBlockStatement(stmt.finalizer);
      this.indent--;
    } else if (!stmt.handler) {
      this.emitLine("}");
    } else {
      this.emitLine("}");
    }
  }

  private emitBlockStatement(stmt: BlockStatement): void {
    for (const s of stmt.statements) {
      this.emitStatement(s);
    }
  }

  private emitReturnStatement(stmt: ReturnStatement): void {
    if (stmt.argument) {
      this.emitLine(`return ${this.emitExpression(stmt.argument)};`);
    } else {
      this.emitLine("return;");
    }
  }

  private emitThrowStatement(stmt: ThrowStatement): void {
    this.emitLine(`throw ${this.emitExpression(stmt.argument)};`);
  }

  private emitImportStatement(stmt: ImportStatement): void {
    if (stmt.defaultImport) {
      if (stmt.specifiers.length > 0) {
        const namedImports = stmt.specifiers.join(", ");
        this.emitLine(`import ${stmt.defaultImport}, { ${namedImports} } from "${stmt.source.replace('.beta', '.js')}";`);
      } else {
        this.emitLine(`import ${stmt.defaultImport} from "${stmt.source.replace('.beta', '.js')}";`);
      }
    } else if (stmt.specifiers.length > 0) {
      const namedImports = stmt.specifiers.join(", ");
      this.emitLine(`import { ${namedImports} } from "${stmt.source.replace('.beta', '.js')}";`);
    }
  }

  private emitExportStatement(stmt: ExportStatement): void {
    if (stmt.declaration.type === "FunctionDeclaration") {
      const decl = stmt.declaration as FunctionDeclaration;
      const asyncKeyword = decl.isAsync ? "async " : "";
      const params = decl.parameters.map(p => `${p.isRest ? "..." : ""}${p.name}`).join(", ");
      this.emitLine(`export async function ${decl.name}(${params}) {`);
      this.indent++;
      this.emitBlockStatement(decl.body);
      this.indent--;
      this.emitLine("}");
    } else if (stmt.declaration.type === "VariableDeclaration") {
      const decl = stmt.declaration as VariableDeclaration;
      const keyword = decl.kind === "ane" ? "let" : "const";
      if (decl.initializer) {
        this.emitLine(`export ${keyword} ${decl.name} = ${this.emitExpression(decl.initializer)};`);
      } else {
        this.emitLine(`export ${keyword} ${decl.name};`);
      }
    } else if (stmt.declaration.type === "ClassDeclaration") {
      const decl = stmt.declaration as ClassDeclaration;
      let classStr = "export class " + decl.name;
      if (decl.superclass) classStr += " extends " + decl.superclass;
      this.emitLine(classStr + " {");
      this.indent++;
      for (const member of decl.members) {
        this.emitClassMember(member);
      }
      this.indent--;
      this.emitLine("}");
    }
  }

  private emitExpressionStatement(stmt: ExpressionStatement): void {
    this.emitLine(`${this.emitExpression(stmt.expression)};`);
  }

  private emitExpression(expr: Expression): string {
    switch (expr.type) {
      case "Identifier":
        if (expr.name === "tungguin") return "await ";
        return expr.name;
      case "Literal":
        if (expr.value === null) return "null";
        if (expr.value === undefined) return "undefined";
        if (typeof expr.value === "string" && (expr.raw.startsWith("`") || expr.raw.startsWith("/"))) return expr.raw;
        if (typeof expr.value === "string") return JSON.stringify(expr.value);
        if (typeof expr.value === "number") return expr.raw;
        return String(expr.value);
      case "BinaryExpression":
        return `(${this.emitExpression(expr.left)} ${expr.operator} ${this.emitExpression(expr.right)})`;
      case "UnaryExpression":
        if (expr.prefix) {
          const op = expr.operator === "await" || expr.operator === "..." ? `${expr.operator} ` : expr.operator;
          return `${op}${this.emitExpression(expr.argument)}`;
        }
        return `${this.emitExpression(expr.argument)}${expr.operator}`;
      case "AssignmentExpression":
        return `(${this.emitExpression(expr.left)} ${expr.operator} ${this.emitExpression(expr.right)})`;
      case "CallExpression":
        return this.emitCallExpression(expr);
      case "MemberExpression":
        return this.emitMemberExpression(expr);
      case "NewExpression":
        return `new ${expr.callee}(${expr.arguments.map(this.emitExpression.bind(this)).join(", ")})`;
      case "SuperExpression":
        const superArgs = expr.arguments ? expr.arguments.map(this.emitExpression.bind(this)).join(", ") : "";
        if (expr.property) {
          // Special case: constructor call becomes just super()
          if (expr.property.name === "constructor") {
            return `super(${superArgs})`;
          }
          return `super.${expr.property.name}(${superArgs})`;
        }
        return `super(${superArgs})`;
      case "ArrayExpression":
        return `[${expr.elements.map(this.emitExpression.bind(this)).join(", ")}]`;
      case "ObjectExpression":
        const props = expr.properties.map(p => {
          if (p.key === "__spread") return `...${this.emitExpression(p.value)}`;
          const key = typeof p.key === "string" ? p.key : this.emitExpression(p.key as Expression);
          return `${key}: ${this.emitExpression(p.value)}`;
        }).join(", ");
        return `{${props}}`;
      case "LambdaExpression":
        const params = expr.parameters.map(p => p.name).join(", ");
        if (expr.body.type === "BlockStatement") {
          const body = this.emitLambdaBody(expr.body);
          return `(${params}) => ${body}`;
        }
        return `(${params}) => ${this.emitExpression(expr.body)}`;
      case "ConditionalExpression":
        return `(${this.emitExpression(expr.test)} ? ${this.emitExpression(expr.consequent)} : ${this.emitExpression(expr.alternate)})`;
    }
  }

  private emitCallExpression(expr: CallExpression): string {
    const callee = this.emitExpression(expr.callee);
    const args = expr.arguments.map(this.emitExpression.bind(this)).join(", ");
    return `${callee}(${args})`;
  }

  private emitMemberExpression(expr: MemberExpression): string {
    const obj = this.emitExpression(expr.object);
    const prop = expr.computed 
      ? `[${this.emitExpression(expr.property)}]` 
      : `${expr.optional ? "?." : "."}${(expr.property as Identifier).name}`;
    return `${obj}${prop}`;
  }

  private emitLambdaBody(body: BlockStatement): string {
    const statements = body.statements.map(s => {
      if (s.type === "ReturnStatement") {
        if (s.argument) return `return ${this.emitExpression(s.argument)};`;
        return "return;";
      }
      return this.emitExpression(s as any);
    });
    return `{ ${statements.join(" ")} }`;
  }

  private emitLine(line: string): void {
    this.output += this.indentString() + line + "\n";
  }

  private indentString(): string {
    return "  ".repeat(this.indent);
  }
}
