// Generated by BetaScript Compiler
const __fs = require("fs");
const __pasang = (proto, nama, fn) => { if (!Object.prototype.hasOwnProperty.call(proto, nama)) Object.defineProperty(proto, nama, { value: fn, configurable: true }); };
const __pasangGet = (proto, nama, fn) => { if (!Object.prototype.hasOwnProperty.call(proto, nama)) Object.defineProperty(proto, nama, { get: fn, configurable: true }); };
__pasang(String.prototype, "gede", function() { return this.toString().toUpperCase(); });
__pasang(String.prototype, "kecil", function() { return this.toString().toLowerCase(); });
__pasang(String.prototype, "pisah", function(separator) { return this.toString().split(separator); });
__pasang(String.prototype, "ganti", function(search, replace) { return this.toString().replace(search, replace); });
__pasang(String.prototype, "cocok", function(pattern) { return this.toString().match(pattern); });
__pasangGet(String.prototype, "sebrapa", function() { return this.length; });
__pasang(Array.prototype, "petakan", function(fn) { return this.map(fn); });
__pasang(Array.prototype, "saring", function(fn) { return this.filter(fn); });
__pasang(Array.prototype, "kurangi", function(fn, init) { return arguments.length > 1 ? this.reduce(fn, init) : this.reduce(fn); });
__pasang(Array.prototype, "urutin", function(fn) { return this.sort(fn); });
__pasang(Array.prototype, "gabung", function(separator) { return this.join(separator); });
__pasangGet(Array.prototype, "sebrapa", function() { return this.length; });
const __runtime = {
teriak: (...args) => console.log(...args),
bisik: (msg) => process.stdout.write(String(msg)),
dengerin: (msg) => require('readline-sync').question(msg),
sebrapa: (arr) => arr?.length ?? 0,
ape: (val) => typeof val,
itungan: (val) => Number(val),
omongan: (val) => String(val),
kumpulin: (...items) => Array(...items),
acak: () => Math.random(),
tidur: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
semua: (promises) => Promise.all(promises),
balap: (promises) => Promise.race(promises),
peta: (entries) => new Map(entries),
himpunan: (values) => new Set(values),
peta_lemah: (entries) => new WeakMap(entries),
himpunan_lemah: (values) => new WeakSet(values)
};

const http = { ambil: (url, options) => fetch(url, options), kirim: (url, data, options = {}) => fetch(url, { ...options, method: options.method || "POST", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, body: typeof data === "string" ? data : JSON.stringify(data) }) };
const file = { baca: (p) => __fs.promises.readFile(p, "utf8"), tulis: (p, data) => __fs.promises.writeFile(p, data, "utf8"), ada: (p) => __fs.existsSync(p) };
const matematika = { pi: Math.PI, akar: Math.sqrt, acak: Math.random, bulat: Math.round, lantai: Math.floor, atap: Math.ceil, mutlak: Math.abs, maksimal: Math.max, minimal: Math.min };
const teks = { gede: (v) => String(v).toUpperCase(), kecil: (v) => String(v).toLowerCase(), pisah: (v, s) => String(v).split(s), ganti: (v, a, b) => String(v).replace(a, b), cocok: (v, pola) => String(v).match(pola) };
const deret = { petakan: (v, fn) => v.map(fn), saring: (v, fn) => v.filter(fn), kurangi: (v, fn, init) => init === undefined ? v.reduce(fn) : v.reduce(fn, init), urutin: (v, fn) => v.sort(fn) };
const waktu = { sekarang: () => new Date(), format: (v) => new Date(v).toISOString() };
const json = { parse: JSON.parse, stringify: JSON.stringify };
const teriak = __runtime.teriak;
const bisik = __runtime.bisik;
const dengerin = __runtime.dengerin;
const sebrapa = __runtime.sebrapa;
const ape = __runtime.ape;
const itungan = __runtime.itungan;
const omongan = __runtime.omongan;
const kumpulin = __runtime.kumpulin;
const acak = __runtime.acak;
const tidur = __runtime.tidur;

const semua = __runtime.semua;
const balap = __runtime.balap;
const peta = __runtime.peta;
const himpunan = __runtime.himpunan;
const peta_lemah = __runtime.peta_lemah;
const himpunan_lemah = __runtime.himpunan_lemah;

teriak("🔥 === 1. LOOP ITUNG (For Loop) ===");
for (let i = 5; (i > 0); i--) {
  teriak(("Hitungan mundur: " + i));
}
teriak("🎉 BOOM! Tahun Baru!");
teriak("\n🔥 === 2. LOOP SELAGI (While Loop) + DAH (Break) ===");
let peluru = 3;
while ((peluru > 0)) {
  teriak(("DOR! Sisa peluru: " + peluru));
  peluru--;
  if ((peluru == 0)) {
    teriak("Yah, peluru abis bang! Cabut dulu ah...");
    break;
  }
}
teriak("\n🔥 === 3. LOOP SABAN (For...of Array) + LANJUT (Continue) ===");
let jajanan = ["Kerak Telor", "Kue Pancong", "Dodol Betawi", "Soto Betawi", "Bir Pletok"];
for (let makanan of jajanan) {
  if ((makanan == "Soto Betawi")) {
    teriak((("Wah, " + makanan) + " mah berat, skip dulu bang!"));
    continue;
  }
  teriak(("Nyam nyam, lagi makan: " + makanan));
}
teriak("\n🔥 === 4. LOOP KERJAIN-SELAGI (Do-While) ===");
let tebakan = 0;
do {
  tebakan++;
  teriak(("Ngecek angka: " + tebakan));
} while ((tebakan < 3));
teriak("\n✅ Beres bang! Semua loop jalan mulus kagak ada error!");
