// Generated by BetaScript Compiler
const __runtime = {
teriak: (...args) => console.log(...args),
bisik: (msg) => process.stdout.write(String(msg)),
dengerin: (msg) => require('readline-sync').question(msg),
sebrapa: (arr) => arr?.length ?? 0,
ape: (val) => typeof val,
itungan: (val) => Number(val),
omongan: (val) => String(val),
kumpulin: (...items) => Array(...items),
acak: () => Math.random(),
tidur: (ms) => new Promise((resolve) => setTimeout(resolve, ms))
};

const teriak = __runtime.teriak;
const bisik = __runtime.bisik;
const dengerin = __runtime.dengerin;
const sebrapa = __runtime.sebrapa;
const ape = __runtime.ape;
const itungan = __runtime.itungan;
const omongan = __runtime.omongan;
const kumpulin = __runtime.kumpulin;
const acak = __runtime.acak;
const tidur = __runtime.tidur;

teriak("🔥 === 1. LOOP ITUNG (For Loop) ===");
for (let i = 5; (i > 0); i--) {
  teriak(("Hitungan mundur: " + i));
}
teriak("🎉 BOOM! Tahun Baru!");
teriak("\n🔥 === 2. LOOP SELAGI (While Loop) + DAH (Break) ===");
let peluru = 3;
while ((peluru > 0)) {
  teriak(("DOR! Sisa peluru: " + peluru));
  peluru--;
  if ((peluru == 0)) {
    teriak("Yah, peluru abis bang! Cabut dulu ah...");
    break;
  }
}
teriak("\n🔥 === 3. LOOP SABAN (For...of Array) + LANJUT (Continue) ===");
let jajanan = ["Kerak Telor", "Kue Pancong", "Dodol Betawi", "Soto Betawi", "Bir Pletok"];
for (let makanan of jajanan) {
  if ((makanan == "Soto Betawi")) {
    teriak((("Wah, " + makanan) + " mah berat, skip dulu bang!"));
    continue;
  }
  teriak(("Nyam nyam, lagi makan: " + makanan));
}
teriak("\n🔥 === 4. LOOP KERJAIN-SELAGI (Do-While) ===");
let tebakan = 0;
do {
  tebakan++;
  teriak(("Ngecek angka: " + tebakan));
} while ((tebakan < 3));
teriak("\n✅ Beres bang! Semua loop jalan mulus kagak ada error!");
