// Generated by BetaScript Compiler
const __runtime = {
teriak: (...args) => console.log(...args),
bisik: (msg) => process.stdout.write(String(msg)),
dengerin: (msg) => require('readline-sync').question(msg),
sebrapa: (arr) => arr?.length ?? 0,
ape: (val) => typeof val,
itungan: (val) => Number(val),
omongan: (val) => String(val),
kumpulin: (...items) => Array(...items),
acak: () => Math.random(),
tidur: (ms) => new Promise((resolve) => setTimeout(resolve, ms))
};

const teriak = __runtime.teriak;
const bisik = __runtime.bisik;
const dengerin = __runtime.dengerin;
const sebrapa = __runtime.sebrapa;
const ape = __runtime.ape;
const itungan = __runtime.itungan;
const omongan = __runtime.omongan;
const kumpulin = __runtime.kumpulin;
const acak = __runtime.acak;
const tidur = __runtime.tidur;

async function ambil_data() {
  teriak("Sabar ya, ambil data...");
  null;
}
async function main() {
  teriak("Mulai");
  await ambil_data();
  teriak("Selesai");
}
main();
